### ISSUE TITLE
SuffixRemover crashes on call

### ISSUE THREAD

**Issue by nagotown** [RyuuseiKang/SuffixRemover#1]
When I run it on OpenUtau v0.0.775.0, it crashes on launch. I tried launching it with all notes selected and unselected.
[log20220528.txt](https://github.com/RyuuseiKang/SuffixRemover/files/8792373/log20220528.txt)

**Comment by ryu-xh** [comment]
Could you please show me the error message created by Suffix Remover?

**Comment by ryu-xh** [comment]
I had you confirm the problem.
Close this issue as soon as it is resolved.

**Comment by ryu-xh** [comment]
I've just solved the problem.
We have uploaded the latest version, so please check it.

[Lastest Release](https://github.com/RyuuseiKang/SuffixRemover/releases/tag/release)

**Comment by nagotown** [comment]
It works now, thanks 👍
